/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.fiap.fase06.grupo10.apipedido.broker.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class PedidoCriado extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2727613706640044889L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"PedidoCriado\",\"namespace\":\"com.fiap.fase06.grupo10.apipedido.broker.schema\",\"fields\":[{\"name\":\"id\",\"type\":\"string\"},{\"name\":\"clienteId\",\"type\":\"string\"},{\"name\":\"restauranteId\",\"type\":\"string\"},{\"name\":\"date\",\"type\":{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}},{\"name\":\"status\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<PedidoCriado> ENCODER =
      new BinaryMessageEncoder<PedidoCriado>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<PedidoCriado> DECODER =
      new BinaryMessageDecoder<PedidoCriado>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<PedidoCriado> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<PedidoCriado> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<PedidoCriado>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this PedidoCriado to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a PedidoCriado from a ByteBuffer. */
  public static PedidoCriado fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence id;
  @Deprecated public java.lang.CharSequence clienteId;
  @Deprecated public java.lang.CharSequence restauranteId;
  @Deprecated public org.joda.time.DateTime date;
  @Deprecated public java.lang.CharSequence status;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public PedidoCriado() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param clienteId The new value for clienteId
   * @param restauranteId The new value for restauranteId
   * @param date The new value for date
   * @param status The new value for status
   */
  public PedidoCriado(java.lang.CharSequence id, java.lang.CharSequence clienteId, java.lang.CharSequence restauranteId, org.joda.time.DateTime date, java.lang.CharSequence status) {
    this.id = id;
    this.clienteId = clienteId;
    this.restauranteId = restauranteId;
    this.date = date;
    this.status = status;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return clienteId;
    case 2: return restauranteId;
    case 3: return date;
    case 4: return status;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  protected static final org.apache.avro.data.TimeConversions.DateConversion DATE_CONVERSION = new org.apache.avro.data.TimeConversions.DateConversion();
  protected static final org.apache.avro.data.TimeConversions.TimeConversion TIME_CONVERSION = new org.apache.avro.data.TimeConversions.TimeConversion();
  protected static final org.apache.avro.data.TimeConversions.TimestampConversion TIMESTAMP_CONVERSION = new org.apache.avro.data.TimeConversions.TimestampConversion();
  protected static final org.apache.avro.Conversions.DecimalConversion DECIMAL_CONVERSION = new org.apache.avro.Conversions.DecimalConversion();

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      TIMESTAMP_CONVERSION,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.CharSequence)value$; break;
    case 1: clienteId = (java.lang.CharSequence)value$; break;
    case 2: restauranteId = (java.lang.CharSequence)value$; break;
    case 3: date = (org.joda.time.DateTime)value$; break;
    case 4: status = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.CharSequence getId() {
    return id;
  }

  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.CharSequence value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'clienteId' field.
   * @return The value of the 'clienteId' field.
   */
  public java.lang.CharSequence getClienteId() {
    return clienteId;
  }

  /**
   * Sets the value of the 'clienteId' field.
   * @param value the value to set.
   */
  public void setClienteId(java.lang.CharSequence value) {
    this.clienteId = value;
  }

  /**
   * Gets the value of the 'restauranteId' field.
   * @return The value of the 'restauranteId' field.
   */
  public java.lang.CharSequence getRestauranteId() {
    return restauranteId;
  }

  /**
   * Sets the value of the 'restauranteId' field.
   * @param value the value to set.
   */
  public void setRestauranteId(java.lang.CharSequence value) {
    this.restauranteId = value;
  }

  /**
   * Gets the value of the 'date' field.
   * @return The value of the 'date' field.
   */
  public org.joda.time.DateTime getDate() {
    return date;
  }

  /**
   * Sets the value of the 'date' field.
   * @param value the value to set.
   */
  public void setDate(org.joda.time.DateTime value) {
    this.date = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public java.lang.CharSequence getStatus() {
    return status;
  }

  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(java.lang.CharSequence value) {
    this.status = value;
  }

  /**
   * Creates a new PedidoCriado RecordBuilder.
   * @return A new PedidoCriado RecordBuilder
   */
  public static com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder newBuilder() {
    return new com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder();
  }

  /**
   * Creates a new PedidoCriado RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new PedidoCriado RecordBuilder
   */
  public static com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder newBuilder(com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder other) {
    return new com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder(other);
  }

  /**
   * Creates a new PedidoCriado RecordBuilder by copying an existing PedidoCriado instance.
   * @param other The existing instance to copy.
   * @return A new PedidoCriado RecordBuilder
   */
  public static com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder newBuilder(com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado other) {
    return new com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder(other);
  }

  /**
   * RecordBuilder for PedidoCriado instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<PedidoCriado>
    implements org.apache.avro.data.RecordBuilder<PedidoCriado> {

    private java.lang.CharSequence id;
    private java.lang.CharSequence clienteId;
    private java.lang.CharSequence restauranteId;
    private org.joda.time.DateTime date;
    private java.lang.CharSequence status;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.clienteId)) {
        this.clienteId = data().deepCopy(fields()[1].schema(), other.clienteId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.restauranteId)) {
        this.restauranteId = data().deepCopy(fields()[2].schema(), other.restauranteId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.date)) {
        this.date = data().deepCopy(fields()[3].schema(), other.date);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing PedidoCriado instance
     * @param other The existing instance to copy.
     */
    private Builder(com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.clienteId)) {
        this.clienteId = data().deepCopy(fields()[1].schema(), other.clienteId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.restauranteId)) {
        this.restauranteId = data().deepCopy(fields()[2].schema(), other.restauranteId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.date)) {
        this.date = data().deepCopy(fields()[3].schema(), other.date);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.status)) {
        this.status = data().deepCopy(fields()[4].schema(), other.status);
        fieldSetFlags()[4] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.CharSequence getId() {
      return id;
    }

    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder setId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'clienteId' field.
      * @return The value.
      */
    public java.lang.CharSequence getClienteId() {
      return clienteId;
    }

    /**
      * Sets the value of the 'clienteId' field.
      * @param value The value of 'clienteId'.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder setClienteId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.clienteId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'clienteId' field has been set.
      * @return True if the 'clienteId' field has been set, false otherwise.
      */
    public boolean hasClienteId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'clienteId' field.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder clearClienteId() {
      clienteId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'restauranteId' field.
      * @return The value.
      */
    public java.lang.CharSequence getRestauranteId() {
      return restauranteId;
    }

    /**
      * Sets the value of the 'restauranteId' field.
      * @param value The value of 'restauranteId'.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder setRestauranteId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.restauranteId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'restauranteId' field has been set.
      * @return True if the 'restauranteId' field has been set, false otherwise.
      */
    public boolean hasRestauranteId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'restauranteId' field.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder clearRestauranteId() {
      restauranteId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'date' field.
      * @return The value.
      */
    public org.joda.time.DateTime getDate() {
      return date;
    }

    /**
      * Sets the value of the 'date' field.
      * @param value The value of 'date'.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder setDate(org.joda.time.DateTime value) {
      validate(fields()[3], value);
      this.date = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'date' field has been set.
      * @return True if the 'date' field has been set, false otherwise.
      */
    public boolean hasDate() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'date' field.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder clearDate() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public java.lang.CharSequence getStatus() {
      return status;
    }

    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder setStatus(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.status = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.fiap.fase06.grupo10.apipedido.broker.schema.PedidoCriado.Builder clearStatus() {
      status = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public PedidoCriado build() {
      try {
        PedidoCriado record = new PedidoCriado();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.CharSequence) defaultValue(fields()[0], record.getConversion(0));
        record.clienteId = fieldSetFlags()[1] ? this.clienteId : (java.lang.CharSequence) defaultValue(fields()[1], record.getConversion(1));
        record.restauranteId = fieldSetFlags()[2] ? this.restauranteId : (java.lang.CharSequence) defaultValue(fields()[2], record.getConversion(2));
        record.date = fieldSetFlags()[3] ? this.date : (org.joda.time.DateTime) defaultValue(fields()[3], record.getConversion(3));
        record.status = fieldSetFlags()[4] ? this.status : (java.lang.CharSequence) defaultValue(fields()[4], record.getConversion(4));
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<PedidoCriado>
    WRITER$ = (org.apache.avro.io.DatumWriter<PedidoCriado>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<PedidoCriado>
    READER$ = (org.apache.avro.io.DatumReader<PedidoCriado>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
