version: '3'

services:     
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: fiap-fase06-grupo10-zookeeper
    restart: always
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: fiap-fase06-grupo10-kafka
    restart: always
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8181:8181
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: zookeeper:2181

  mongo-pedido:
    image: mongo
    container_name: fiap-fase06-grupo10-mongo-pedido
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  api-pedido:
    build:
      context: fase06-api-pedido
      dockerfile: Dockerfile
    container_name: fiap-fase06-grupo10-api-pedido
    restart: always
    depends_on: [kafka,mongo-pedido]
    environment:
        MONGO_REPLICA:
        MONGODB_NAME: pedido
        MONGODB_HOST: mongo-pedido
        MONGODB_PARAM: authSource=admin
        KAFKA_BROKER_URL: kafka:9092
        
  # api-pagamento:
  #   build:
  #     context: api-pagamento
  #     dockerfile: src/main/docker/Dockerfile
  #   container_name: fiap-fase06-grupo10-api-pagamento
  #   restart: always
  #   depends_on: [kafka]
  #   environment:
  #      KAFKA_BROKER_URL: kafka:9092  
           
