server:
  port: 8080

spring:
  cloud:
    stream:
      default:
        producer:
          useNativeEncoding: true
      bindings:
        output:
          destination: topic-pedido
          content-type: application/*+avro
      kafka:
        binder:
          producer-properties:
            key:
              serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            value:
              serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
            schema:
              registry:
                url: http://localhost:8181

  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/pedido

logging:
  level:
    com.fiap.fase06.grupo10.apipedido: info

